"""initial schema

Revision ID: 5dd4776d88ef
Revises:
Create Date: 2026-02-22 10:02:56.740796

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5dd4776d88ef"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("initial_balance", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "category",
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("category_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "posting",
        sa.Column("posting_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("posting_date", sa.Date(), nullable=False),
        sa.Column("category_id", sa.String(length=36), nullable=True),
        sa.Column("posting_type", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.category_id"],
        ),
        sa.PrimaryKeyConstraint("posting_id"),
    )
    op.create_table(
        "transfer",
        sa.Column("transfer_id", sa.String(length=36), nullable=False),
        sa.Column("source_account_id", sa.String(length=36), nullable=False),
        sa.Column("dest_account_id", sa.String(length=36), nullable=False),
        sa.Column("debit_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("credit_amount", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("transfer_date", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["dest_account_id"],
            ["account.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_account_id"],
            ["account.account_id"],
        ),
        sa.PrimaryKeyConstraint("transfer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transfer")
    op.drop_table("posting")
    op.drop_table("category")
    op.drop_table("account")
    # ### end Alembic commands ###
